apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines-as-code
  namespace: pipelines-as-code
data:
  # Enable the new abstracted concurrency system
  concurrency-enabled: "true"

  # Choose the driver: "etcd", "postgresql", or "memory"
  concurrency-driver: "etcd"

  # etcd configuration (when using etcd driver)
  etcd-endpoints: "localhost:2379"
  etcd-dial-timeout: "5s"
  # "etcd", "mock", or "memory"
  etcd-mode: "etcd"
  # etcd-username: "etcd_user"
  # etcd-password: "etcd_password"
  # etcd-cert-file: "/path/to/cert.pem"
  # etcd-key-file: "/path/to/key.pem"
  # etcd-ca-file: "/path/to/ca.pem"
  # etcd-server-name: "etcd.example.com"

  # PostgreSQL configuration (when using postgresql driver)
  # postgresql-host: "localhost"
  # postgresql-port: "5432"
  # postgresql-database: "pac_concurrency"
  # postgresql-username: "pac_user"
  # postgresql-password: "pac_password"
  # postgresql-ssl-mode: "disable"
  # postgresql-max-connections: "10"
  # postgresql-connection-timeout: "30s"
  # postgresql-lease-ttl: "1h"

  # Memory configuration (when using memory driver - for testing only)
  # memory-lease-ttl: "30m"
