package llm

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/openshift-pipelines/pipelines-as-code/pkg/apis/pipelinesascode/v1alpha1"
	"github.com/openshift-pipelines/pipelines-as-code/pkg/params"
	"github.com/openshift-pipelines/pipelines-as-code/pkg/params/info"
	"github.com/openshift-pipelines/pipelines-as-code/pkg/provider"
	tektonv1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	"go.uber.org/zap"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OutputHandler handles the output of LLM analysis results to various destinations.
type OutputHandler struct {
	run    *params.Run
	logger *zap.SugaredLogger
}

// NewOutputHandler creates a new output handler.
func NewOutputHandler(run *params.Run, logger *zap.SugaredLogger) *OutputHandler {
	return &OutputHandler{
		run:    run,
		logger: logger,
	}
}

// HandleOutput processes the LLM analysis output according to the role configuration.
func (h *OutputHandler) HandleOutput(ctx context.Context, repo *v1alpha1.Repository, pr *tektonv1.PipelineRun, result AnalysisResult, event *info.Event, prov provider.Interface) error {
	if repo.Spec.Settings == nil || repo.Spec.Settings.AIAnalysis == nil {
		return fmt.Errorf("AI analysis configuration is nil")
	}

	// Find the role configuration
	var roleConfig *v1alpha1.AnalysisRole
	for _, role := range repo.Spec.Settings.AIAnalysis.Roles {
		if role.Name == result.Role {
			roleConfig = &role
			break
		}
	}

	if roleConfig == nil {
		return fmt.Errorf("role configuration not found for %s", result.Role)
	}

	// Handle different output destinations
	switch roleConfig.Output {
	case "pr-comment":
		return h.handlePRComment(ctx, result, event, prov)
	case "check-run":
		return h.handleCheckRun(ctx, result, event, prov)
	case "annotation":
		return h.handleAnnotation(ctx, result, pr)
	default:
		return fmt.Errorf("unsupported output destination: %s", roleConfig.Output)
	}
}

// handlePRComment posts LLM analysis as a PR comment.
func (h *OutputHandler) handlePRComment(ctx context.Context, result AnalysisResult, event *info.Event, prov provider.Interface) error {
	if event.PullRequestNumber == 0 {
		h.logger.Debug("No pull request associated with this event, skipping PR comment")
		return nil
	}

	// Format the comment with LLM analysis
	comment := fmt.Sprintf("## 🤖 AI Analysis - %s\n\n%s\n\n---\n*Generated by Pipelines-as-Code LLM Analysis*",
		result.Role, result.Response.Content)

	// Create a unique marker for this analysis role to allow updates
	updateMarker := fmt.Sprintf("llm-analysis-%s", result.Role)

	if err := prov.CreateComment(ctx, event, comment, updateMarker); err != nil {
		return fmt.Errorf("failed to create PR comment: %w", err)
	}

	h.logger.Infof("Posted LLM analysis as PR comment for role %s", result.Role)
	return nil
}

// handleCheckRun creates a check run with LLM analysis.
func (h *OutputHandler) handleCheckRun(ctx context.Context, result AnalysisResult, event *info.Event, prov provider.Interface) error {
	// For check runs, we need to determine the conclusion based on the pipeline status
	conclusion := "neutral" // Default for informational analysis

	// If this is a failure analysis and we have structured output, we might set it to "failure"
	// For now, we'll keep it neutral as it's an advisory analysis

	status := provider.StatusOpts{
		Status:                  "completed",
		Conclusion:              conclusion,
		Title:                   fmt.Sprintf("AI Analysis - %s", result.Role),
		Summary:                 result.Response.Content,
		Text:                    result.Response.Content,
		PipelineRunName:         fmt.Sprintf("llm-analysis-%s", result.Role),
		OriginalPipelineRunName: fmt.Sprintf("llm-analysis-%s", result.Role),
	}

	if err := prov.CreateStatus(ctx, event, status); err != nil {
		return fmt.Errorf("failed to create check run: %w", err)
	}

	h.logger.Infof("Created check run for LLM analysis role %s", result.Role)
	return nil
}

// handleAnnotation adds LLM analysis as pipeline run annotations.
func (h *OutputHandler) handleAnnotation(ctx context.Context, result AnalysisResult, pr *tektonv1.PipelineRun) error {
	if result.Response == nil {
		return fmt.Errorf("no response to store in annotations")
	}

	// Get the latest version of the PipelineRun to avoid conflicts
	latestPR, err := h.run.Clients.Tekton.TektonV1().PipelineRuns(pr.Namespace).Get(
		ctx,
		pr.Name,
		metav1.GetOptions{},
	)
	if err != nil {
		return fmt.Errorf("failed to get PipelineRun: %w", err)
	}

	// Prepare annotation key
	annotationKey := fmt.Sprintf("pipelinesascode.tekton.dev/llm-analysis-%s", result.Role)

	// Prepare annotation value with metadata
	analysisData := map[string]interface{}{
		"role":        result.Role,
		"provider":    result.Response.Provider,
		"timestamp":   result.Response.Timestamp.Format("2006-01-02T15:04:05Z07:00"),
		"tokens_used": result.Response.TokensUsed,
		"duration_ms": result.Response.Duration.Milliseconds(),
		"content":     result.Response.Content,
	}

	// If JSON output was requested and parsed, include it
	if result.Response.JSONParsed != nil {
		analysisData["json_parsed"] = result.Response.JSONParsed
	}

	// Marshal to JSON
	jsonData, err := json.Marshal(analysisData)
	if err != nil {
		return fmt.Errorf("failed to marshal analysis data: %w", err)
	}

	// Check size and truncate if necessary
	// Kubernetes annotation limit is 256KB, we use 200KB as safe limit
	const maxAnnotationSize = 200000
	annotationValue := string(jsonData)

	if len(annotationValue) > maxAnnotationSize {
		h.logger.Warnf("Analysis content for role %s exceeds size limit (%d bytes), truncating",
			result.Role, len(annotationValue))

		// Try to truncate just the content field
		content := result.Response.Content
		availableSize := maxAnnotationSize - (len(annotationValue) - len(content)) - 100 // buffer for truncation message

		if availableSize > 0 {
			truncationMsg := "\n\n...[Content truncated due to size limits]"
			if availableSize > len(truncationMsg) {
				analysisData["content"] = content[:availableSize-len(truncationMsg)] + truncationMsg
			} else {
				analysisData["content"] = "[Content too large to store]"
			}
			analysisData["truncated"] = true

			jsonData, err = json.Marshal(analysisData)
			if err != nil {
				return fmt.Errorf("failed to marshal truncated analysis data: %w", err)
			}
			annotationValue = string(jsonData)
		} else {
			return fmt.Errorf("analysis content too large to store in annotations even after truncation")
		}
	}

	// Update annotations
	if latestPR.Annotations == nil {
		latestPR.Annotations = make(map[string]string)
	}
	latestPR.Annotations[annotationKey] = annotationValue

	// Patch the PipelineRun
	_, err = h.run.Clients.Tekton.TektonV1().PipelineRuns(latestPR.Namespace).Update(
		ctx,
		latestPR,
		metav1.UpdateOptions{},
	)
	if err != nil {
		return fmt.Errorf("failed to update PipelineRun annotations: %w", err)
	}

	h.logger.Infof("Successfully stored LLM analysis for role %s in PipelineRun annotations (size: %d bytes)",
		result.Role, len(annotationValue))
	return nil
}
